name: Teste Cron

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - name: Teste Cron Ativo
        run: echo "Cron funcionando"
